### ISSUE TITLE
User credentials not working after restart

### ISSUE THREAD

**Issue by LiskoSlayer63** [Valandur/Web-API#53]
Everytime I restart my server I cannot login to the admin page, it just says that "Invalid username or password" and I need to manually set a new password.

**Web-API version**: 4.8.2-S7.0
**SpongeForge version**: 2529-7.0.0-BETA-2736
**Forge version**: 14.23.0.2544
**Minecraft version**: 1.12.2

**Comment by Valandur** [comment]
Hi, thanks for reporting this. This is obviously not supposed to happen. Can you check to see what is in the users config file `config/webapi/users.conf`? The user should be saved in there when you create him. Possible the location is not read/write accessible?

**Comment by LiskoSlayer63** [comment]
Oh, I forgot to mention that I had already checked that file. It saves the user what I created and the odd part is, that the file remains unaffected after reboot (it doesn't remove the user or change it's password hash). I also use Windows so there shouldn't be problem with the write/read permissions.

**Comment by Valandur** [comment]
When running the command `/webapi users list` from ingame or the server console, does that list the user you created?  
Are you creating the user with `/webapi users add <user> <password>` or without the password? What happens when you reload the Web-API without restarting the server (`/sponge plugins reload` from ingame or server console)?

**Comment by Valandur** [comment]
Are you still having this issue, and do you have any more information about it?

**Comment by LiskoSlayer63** [comment]
@Valandur Sorry about the late answer, didn't have enough time earlier. I need to test the newest version after I've updated Forge & Sponge. I'll report here what happens!

**Comment by Valandur** [comment]
Ahhhhh now I understand what's happening. The problem is that the user file isn't saved after changing a password, only when creating a new user.  
As a workaround for now what you can do is delete the user (in the file) and then create a new user with the new password, that should work.  
My apologies, I was a little confused as to what was going wrong.
