### ISSUE TITLE
Server Always crashes when I put in WEBAPI

### ISSUE THREAD

**Issue by Staylin25** [Valandur/Web-API#54]
Crash Report: 
[crash-2017-11-22_01.12.15-server.txt](https://github.com/Valandur/Web-API/files/1493485/crash-2017-11-22_01.12.15-server.txt)

**Comment by Valandur** [comment]
According to the crash report the error you are getting is from EnderIO. I am assuming you tried removing Web-API and running it without it, and it worked?  
If that is the case then this seems to be compatibility issue between Web-API and EnderIO. I look into this ASAP. It would be helpful if you could try running your server without EnderIO but with Web-API, and tell me how that goes.

**Comment by Staylin25** [comment]
Works without EnderIO, pop it back in, errors; pop WebAPI out (with EnderIO still in) works.

**Comment by Valandur** [comment]
I was able to reproduce this issue exactly as you mentioned, and I'll be looking into it. I'm not sure if this is an issue on my end or with EnderIO, but I will most likely be creating a reference issue on the EnderIO github and link it here. It seems to be a dependency problem.

**Comment by Valandur** [comment]
EnderIO issue can be found [here](https://github.com/SleepyTrousers/EnderIO/issues/4364)

**Comment by HenryLoenwind** [comment]
ok, I had a look at this.

```
Caused by: java.util.ServiceConfigurationError: javax.xml.stream.XMLInputFactory: Provider com.ctc.wstx.stax.WstxInputFactory not found
```

You're configuring Java's XML library to use another XML parser (com.ctc.wstx.stax.WstxInputFactory), but that then cannot be found.

FYI, our code:

```
    XMLInputFactory inputFactory = XMLInputFactory.newInstance();
```

**Comment by Valandur** [comment]
Hmm, that seems weird because I'm not actually configuring anything for the XMLParser. I just looked through my code and it looks like I'm not even using the woodstox library explicitly. I remember reading somewhere that woodstox is recommended because it is a lot faster than the java default implementation. I assume woodstox changes the java default XML library automatically.  
Thanks for taking a look, sorry for the inconvenience

**Comment by HenryLoenwind** [comment]
Yeah, quick Google-foo tells me that those Factories scan the whole classpath and use the first impl they find. So this may be caused by you shading it---the Factory finds it, but then tries to load it using its unshaded class name?

**Comment by Valandur** [comment]
Ok so what I was able to figure out is that using `XMLInputFactory inputFactory = XMLInputFactory.newInstance()` java checks the system property (environment variable) `javax.xml.stream.XMLInputFactory` for which class to use as the XML input factory.  

The woodstox library sets this to their own class [here](https://github.com/FasterXML/woodstox/blob/master/src/main/resources/META-INF/services/javax.xml.stream.XMLInputFactory) with a file in `META-INF/services`. After the class is shaded it cannot be found anymore (obviously), but for some reason also when it's not shaded (I believe forge might be doing something here, to usually help avoid plugins clashing with namespaces).  

What I'm going to do for my plugin is remove the file in `META-INF/services`, and manually use the woodstox parser. I would also recommend that you guys might consider explicitly using an XML library, because according to [some](https://stackoverflow.com/questions/17807123/how-to-override-a-service-provider-in-java) [posts](https://stackoverflow.com/questions/5084583/how-to-specify-which-stax-parser-to-use) the indirection provides almost no value.  

Thanks again for the help
