### ISSUE TITLE
Multi server support?

### ISSUE THREAD

**Issue by johnfg10** [Valandur/Web-API#6]
hey,
is there any sort of multi server support currently? maybe server ids or something similar?

**Comment by Valandur** [comment]
Do you mean for multiple minecraft servers running on the same physical server, or for distributed minecraft servers using something like bungeecord?

**Comment by johnfg10** [comment]
ye

**Comment by Valandur** [comment]
I looked into this a bit and it seems to be rather complicated, because I would have to transfer data between JVM's, and that would add a certain delay to every request.

I think currently the easiest way to go about this would be to run the Web-API's on different ports, and then keep a server <-> port map on the server that is accessing the APIs.

I'm also not sure if there are many use cases where multiple minecraft servers would need the same Web-API, but if you can find some good examples I might think about it again.

**Comment by Valandur** [comment]
When looking at this request again, together with others like #51 and #52, I have decided to try how well the Web-API would run when using an external web server.  

This would mean there will be one master server/instance of Web-API, which isn't running as a Minecraft plugin, but standalone (and possibly as an integration to other web servers). This master instance would accept connections from multiple Web-API plugin instances (which would be running on different Minecraft servers), and offer one single endpoint where data can be accessed.  

A good option for this would be [redis](https://redis.io/), because I would be able to use this as a cache at the master server to improve performance. It would however require one server to have a redis instance running (I don't know how practical that is...) 
I have also looked at [RabbitMQ](https://www.rabbitmq.com/) as a possible solution to exchange data between the servers (but this is more involved in setting up, and is just messaging, not a cache like redis)  

The main problem with most of these solutions is that they will require an additional software, which most times you can't install on a simple web server. And just forwarding requests to the local Minecraft servers is something that is easy to do without the help of Web-API

**Comment by Valandur** [comment]
This is now possible since version v4.10.4 and documented here https://github.com/Valandur/admin-panel#external

**Comment by Valandur** [comment]
Multi servers are now officially supported, also in the built in AdminPanel. I will be closing this issue, feel free to open a new one if you have further requests or something doesn't work
